name: Build Android APK v1.0 (fat APK, stable)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Disable Gradle FS watching (stability)
        run: echo "org.gradle.vfs.watch=false" >> android/gradle.properties

      - name: Build fat APK (no split, no shrink)
        run: |
          flutter clean
          # 不拆 ABI、不瘦图标，最接近“初版成功”的构建方式
          flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
